[package]
name = "mempool-rebroadcaster"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mempool-rebroadcaster"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dotenvy = "0.15.7"
alloy = { version = "1.0.22", features = ["full"] }

[dev-dependencies]
tempfile = "3.8"
