[package]
name = "flashblocks-archiver"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
metrics = { workspace = true }
metrics-derive = { workspace = true }
tokio-tungstenite = { version = "0.26.2", features = ["native-tls"] }
sqlx = { version = "0.8.6", features = [
    "runtime-tokio-native-tls",
    "postgres",
    "uuid",
    "chrono",
    "json",
] }
uuid = { version = "1.6.1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
anyhow = "1.0"
futures-util = "0.3"
url = { version = "2.4", features = ["serde"] }
brotli = "8.0.1"

# alloy
alloy-primitives = { version = "1.2.0", default-features = false, features = [
    "map-foldhash",
] }
alloy-genesis = { version = "1.0.23", default-features = false }
alloy-eips = { version = "1.0.23", default-features = false }
alloy-rpc-types = { version = "1.0.23", default-features = false }
alloy-rpc-types-engine = { version = "1.0.23", default-features = false }
alloy-rpc-types-eth = { version = "1.0.23" }
alloy-consensus = { version = "1.0.23" }
alloy-trie = { version = "0.9.0", default-features = false }
alloy-provider = { version = "1.0.23" }
alloy-hardforks = { version = "0.2.12" }
alloy-rpc-client = { version = "1.0.23" }

# op-alloy
op-alloy-rpc-types = { version = "0.18.12", default-features = false }
op-alloy-rpc-types-engine = { version = "0.18.12", default-features = false }
op-alloy-rpc-jsonrpsee = { version = "0.18.12", default-features = false }
op-alloy-network = { version = "0.18.12", default-features = false }
op-alloy-consensus = { version = "0.18.12", default-features = false }


# reth
reth = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-optimism-node = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-optimism-cli = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-rpc-eth-api = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-optimism-primitives = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0", features = [
    "serde",
] }
reth-rpc-convert = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-optimism-rpc = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-optimism-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-optimism-chainspec = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-provider = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-tracing = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-e2e-test-utils = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-primitives-traits = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-evm = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }
reth-cli-util = { git = "https://github.com/paradigmxyz/reth", tag = "v1.6.0" }

# rollup boost
rollup-boost = { git = "http://github.com/flashbots/rollup-boost", rev = "98fff8e059870d192739dd42d41f5244c49f4b9c" }
rustls = "0.23.23"

[[bin]]
name = "flashblocks-archiver"
path = "src/main.rs"

[dev-dependencies]
testcontainers = "0.23"
testcontainers-modules = { version = "0.11", features = ["postgres"] }
tempfile = "3.8"
tokio-test = "0.4"
